# Generated by Django 3.0.5 on 2021-03-23 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('imageURL', models.URLField(default='https://i.imgur.com/4zsBXBE.png')),
                ('bio', models.TextField()),
                ('joinedOn', models.DateTimeField(default=datetime.datetime.now)),
                ('badge', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('tasksCompleted', djongo.models.fields.ArrayReferenceField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.TaskTodo')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('imageURL', models.URLField()),
                ('postedOn', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='account.User')),
                ('linkedTask', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='task.TaskTodo')),
            ],
        ),
    ]
