# Generated by Django 2.2.8 on 2021-03-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasksCompleted',
        ),
        migrations.AddField(
            model_name='user',
            name='tasksCompleted',
            field=models.ManyToManyField(blank=True, to='task.TaskTodo'),
        ),
    ]
