# Generated by Django 3.0.5 on 2021-03-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
