# Generated by Django 3.0.5 on 2021-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210323_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageURL',
            field=models.URLField(default='https://i.imgur.com/4zsBXBE.png'),
        ),
    ]
