# Generated by Django 3.0.5 on 2021-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('worthPoints', models.IntegerField()),
                ('taskType', models.CharField(choices=[('W', 'Weekly'), ('G', 'General')], max_length=1)),
            ],
        ),
    ]
