# Generated by Django 3.0.5 on 2021-03-23 12:40

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210323_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default=utils.utils.generateUUID, max_length=100, primary_key=True, serialize=False),
        ),
    ]
